CREATE TABLE IF NOT EXISTS `TITULACION` (
    `id` TINYINT AUTO_INCREMENT,
    `nombre` VARCHAR(150) NOT NULL,
    `campus` VARCHAR(100) NOT NULL,
    `codigo` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `DEPARTAMENTO` (
    `id` SMALLINT AUTO_INCREMENT,
    `nombre` VARCHAR(150) NOT NULL,
    `codigo` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PROFESOR` (
    `id` SMALLINT AUTO_INCREMENT,
    `dni` VARCHAR(45) NOT NULL,
    `nombre` VARCHAR(100) NOT NULL,
    `cod_departamento` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `AREA` (
    `id` SMALLINT AUTO_INCREMENT,
    `nombre` VARCHAR(150) NOT NULL,
    `departamento` SMALLINT NOT NULL,
    `codigo` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (departamento) REFERENCES DEPARTAMENTO(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ASIGNATURA` (
    `id` SMALLINT AUTO_INCREMENT,
    `nombre` VARCHAR(100) NOT NULL,
    `titulacion` TINYINT NOT NULL,
    `codigo` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (titulacion) REFERENCES TITULACION(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PROFESOR_ASIGNATURA` (
    `id_profesor` SMALLINT,
    `id_asignatura` SMALLINT,
    PRIMARY KEY (`id_profesor`, `id_asignatura`),
    FOREIGN KEY (id_profesor) REFERENCES PROFESOR(id) ON DELETE CASCADE,
    FOREIGN KEY (id_asignatura) REFERENCES ASIGNATURA(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GRUPO` (
    `id` SMALLINT AUTO_INCREMENT,
    `tag` VARCHAR(20) NOT NULL,
    `asignatura` SMALLINT NOT NULL,
    `horas` FLOAT,
    PRIMARY KEY (`id`),
    FOREIGN KEY (asignatura) REFERENCES ASIGNATURA(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
